source ~/.zsh/checks.sh
source ~/.zsh/opts.sh
source ~/.zsh/completion.sh
source ~/.zsh/exports.sh
source ~/.zsh/functions.sh
source ~/.zsh/keys.sh
source ~/.zsh/prompt.sh
source ~/.zsh/alias.sh
source /usr/share/zsh/plugins/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
source /usr/share/fzf/completion.zsh
source /usr/share/fzf/key-bindings.zsh
