#!/bin/sh

format_size() {
    awk '
    function human(x) {
        if (x<1000) {return x}
        s="kMGTEPZY";
        while (x>=1000 && length(s)>1)
            {x/=1000; s=substr(s,2)}
        return int(x+0.5) substr(s,1,1)
    }
    {sub(/^[0-9]+/, human($1)); print}'
}

round() {
    awk '{printf "%.2f", $1}'
}

FREE="$(free | grep $BLOCK_INSTANCE)"

USED_PERCENT=$(echo "$FREE" | awk '{print $3/$2 * 100.0}' | round)
FREE_PERCENT=$(echo "$FREE" | awk '{print $4/$2 * 100.0}' | round)

USED_ABSOLUTE=$(echo "$FREE" | awk '{print $3}' | format_size)
FREE_ABSOLUTE=$(echo "$FREE" | awk '{print $4}' | format_size)
TOTAL=$(echo "$FREE" | awk '{printf $2}' | format_size)

echo "$USED_PERCENT% ($USED_ABSOLUTE / $TOTAL)" # full_text
echo "$USED_PERCENT%" # short_text

if [ $(echo "$USED_PERCENT > 90" | bc) -eq 1 ]; then
    exit 33
fi
