#!/bin/sh

ACPI="$(acpi | grep "Battery $BLOCK_INSTANCE")"

if [ $? -ne 0 ]; then
    exit
fi

drop_comma() {
    sed 's/,$//; s/%//'
}

icon() {
    if [ "$1" = "Full" ]; then
        printf ""
    elif [ $(echo "$2 < 25" | bc) -eq 1 ]; then
        printf ""
    elif [ $(echo "$2 < 50" | bc) -eq 1 ]; then
        printf ""
    elif [ $(echo "$2 < 75" | bc) -eq 1 ]; then
        printf ""
    elif [ $(echo "$2 < 95" | bc) -eq 1 ]; then
        printf ""
    else
        printf ""
    fi

    if [ "$1" = "Charging" ]; then
        printf  "  \n"
    fi
}

state="$(echo "$ACPI" | awk '{print $3}' | drop_comma)"
percent="$(echo "$ACPI" | awk '{print $4}' | drop_comma)"
time="$(echo "$ACPI" | awk '{print $5}' | drop_comma)"

echo "$(icon $state $percent) $percent% $time"
echo "$(icon $state $percent) $percent%"

if [ $(echo "$percent < 20" | bc) -eq 1 ] && [ "$state" != "Charging" ]; then
    exit 33
fi
